package BusinessRules.sandbox;

/*Generated by MPS */


public class map_Rule {
  protected static Object[] From(boolean CashClient, boolean MoneyMarketSecurity, boolean TreasuryBillSecurity, int TransactionDate) {
    // Number of days from contract to settlement
    // The following cases settle immediately
    if (CashClient) {
      return new Object[]{0};
    }
    // In other cases, until June 7, 1995, it was 5 days
    if (TransactionDate < 19950607) {
      return new Object[]{5};
    }
    // From then until September 5, 2017 it was 3 days
    if (TransactionDate < 20170905) {
      return new Object[]{3};
    }
    // From then until now, it is 2 days
    return new Object[]{2};
  }

  public static void main(String[] args) {
    System.out.println("Running tests...");
    test(sameAs(0, From(true, false, false, 20210801)));
    test(sameAs(0, From(false, true, false, 20210801)));
  }
  private static boolean sameAs(Object[] a, Object[] b) {
    if (a.length != b.length) {
      return false;
    }
    int i = 0;
    for (; i < a.length; i = i + 1) {
      if (!(a[i].equals(b[i]))) {
        return false;
      }
    }
    return true;
  }
  private static void test(boolean b) {
    if (b) {
      System.out.println("Test succeeded.");
    } else {
      System.out.println("Test failed");
    }
  }
}
