package BusinessRules.sandbox;

/*Generated by MPS */


public class map_Rule {
  protected static int From(boolean CashClient, boolean MoneyMarketSecurity, boolean TreasuryBillSecurity, int TransactionDate) {
    // Number of days from contract to settlement
    // The following cases settle immediately
    if (CashClient) {

      return 0;
    }
    // In other cases, until June 7, 1995, it was 5 days
    if (TransactionDate < 19950607) {

      return 5;
    }
    // From then until September 5, 2017 it was 3 days
    if (TransactionDate < 20170905) {

      return 3;
    }
    // From then until now, it is 2 days
    return 2;
  }

  public static void main(String[] args) {
    System.out.println("Running tests...");
    test(0 == From(true, false, false, 20210801));
    test(0 == From(false, true, false, 20210801));
  }
  private static void test(boolean b) {
    if (b) {
      System.out.println("Test succeeded.");
    } else {
      System.out.println("Test failed");
    }
  }
}
