package APL.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Comment_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Constant_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Function_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new IfStatement_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Or_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Parameter_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new ParameterReference_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new ResultAssignmanet_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ParameterReference_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af4fcfaL), MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af6946eL), MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af4fcf5L), MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af6b8dcL), MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af78f39L), MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af4fd33L), MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af70b7cL), MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af7c8f2L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x3aadf529c1324900L, 0x9d62756478c3e71aL, 0x13975c775af70b7cL)).seal();
}
