package BusinessRules.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAll = createDescriptorForAll();
  /*package*/ final ConceptDescriptor myConceptAny = createDescriptorForAny();
  /*package*/ final ConceptDescriptor myConceptBefore = createDescriptorForBefore();
  /*package*/ final ConceptDescriptor myConceptBoolean = createDescriptorForBoolean();
  /*package*/ final ConceptDescriptor myConceptComment = createDescriptorForComment();
  /*package*/ final ConceptDescriptor myConceptDate = createDescriptorForDate();
  /*package*/ final ConceptDescriptor myConceptDatePicker = createDescriptorForDatePicker();
  /*package*/ final ConceptDescriptor myConceptElseStatement = createDescriptorForElseStatement();
  /*package*/ final ConceptDescriptor myConceptIfStatement = createDescriptorForIfStatement();
  /*package*/ final ConceptDescriptor myConceptInteger = createDescriptorForInteger();
  /*package*/ final ConceptDescriptor myConceptLessThan = createDescriptorForLessThan();
  /*package*/ final ConceptDescriptor myConceptMinus = createDescriptorForMinus();
  /*package*/ final ConceptDescriptor myConceptNotLessThan = createDescriptorForNotLessThan();
  /*package*/ final ConceptDescriptor myConceptParameter = createDescriptorForParameter();
  /*package*/ final ConceptDescriptor myConceptParameterReferenceBoolean = createDescriptorForParameterReferenceBoolean();
  /*package*/ final ConceptDescriptor myConceptParameterReferenceDate = createDescriptorForParameterReferenceDate();
  /*package*/ final ConceptDescriptor myConceptParameterReferenceInteger = createDescriptorForParameterReferenceInteger();
  /*package*/ final ConceptDescriptor myConceptReturn0Days = createDescriptorForReturn0Days();
  /*package*/ final ConceptDescriptor myConceptReturn1Day = createDescriptorForReturn1Day();
  /*package*/ final ConceptDescriptor myConceptReturn2Days = createDescriptorForReturn2Days();
  /*package*/ final ConceptDescriptor myConceptReturn3Days = createDescriptorForReturn3Days();
  /*package*/ final ConceptDescriptor myConceptReturn5Days = createDescriptorForReturn5Days();
  /*package*/ final ConceptDescriptor myConceptReturnExpression = createDescriptorForReturnExpression();
  /*package*/ final ConceptDescriptor myConceptReturnMultiple = createDescriptorForReturnMultiple();
  /*package*/ final ConceptDescriptor myConceptRule = createDescriptorForRule();
  /*package*/ final ConceptDescriptor myConceptTest = createDescriptorForTest();
  /*package*/ final ConceptDescriptor myConceptTestParameterValue = createDescriptorForTestParameterValue();
  /*package*/ final ConceptDescriptor myConceptType = createDescriptorForType();
  /*package*/ final ConceptDescriptor myConceptTypeBoolean = createDescriptorForTypeBoolean();
  /*package*/ final ConceptDescriptor myConceptTypeDate = createDescriptorForTypeDate();
  /*package*/ final ConceptDescriptor myConceptValue = createDescriptorForValue();
  /*package*/ final ConceptDescriptor myConceptValueBoolean = createDescriptorForValueBoolean();
  /*package*/ final ConceptDescriptor myConceptValueInteger = createDescriptorForValueInteger();
  /*package*/ final ConceptDescriptor myConceptValueMultiple = createDescriptorForValueMultiple();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAll, myConceptAny, myConceptBefore, myConceptBoolean, myConceptComment, myConceptDate, myConceptDatePicker, myConceptElseStatement, myConceptIfStatement, myConceptInteger, myConceptLessThan, myConceptMinus, myConceptNotLessThan, myConceptParameter, myConceptParameterReferenceBoolean, myConceptParameterReferenceDate, myConceptParameterReferenceInteger, myConceptReturn0Days, myConceptReturn1Day, myConceptReturn2Days, myConceptReturn3Days, myConceptReturn5Days, myConceptReturnExpression, myConceptReturnMultiple, myConceptRule, myConceptTest, myConceptTestParameterValue, myConceptType, myConceptTypeBoolean, myConceptTypeDate, myConceptValue, myConceptValueBoolean, myConceptValueInteger, myConceptValueMultiple);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.All:
        return myConceptAll;
      case LanguageConceptSwitch.Any:
        return myConceptAny;
      case LanguageConceptSwitch.Before:
        return myConceptBefore;
      case LanguageConceptSwitch.Boolean:
        return myConceptBoolean;
      case LanguageConceptSwitch.Comment:
        return myConceptComment;
      case LanguageConceptSwitch.Date:
        return myConceptDate;
      case LanguageConceptSwitch.DatePicker:
        return myConceptDatePicker;
      case LanguageConceptSwitch.ElseStatement:
        return myConceptElseStatement;
      case LanguageConceptSwitch.IfStatement:
        return myConceptIfStatement;
      case LanguageConceptSwitch.Integer:
        return myConceptInteger;
      case LanguageConceptSwitch.LessThan:
        return myConceptLessThan;
      case LanguageConceptSwitch.Minus:
        return myConceptMinus;
      case LanguageConceptSwitch.NotLessThan:
        return myConceptNotLessThan;
      case LanguageConceptSwitch.Parameter:
        return myConceptParameter;
      case LanguageConceptSwitch.ParameterReferenceBoolean:
        return myConceptParameterReferenceBoolean;
      case LanguageConceptSwitch.ParameterReferenceDate:
        return myConceptParameterReferenceDate;
      case LanguageConceptSwitch.ParameterReferenceInteger:
        return myConceptParameterReferenceInteger;
      case LanguageConceptSwitch.Return0Days:
        return myConceptReturn0Days;
      case LanguageConceptSwitch.Return1Day:
        return myConceptReturn1Day;
      case LanguageConceptSwitch.Return2Days:
        return myConceptReturn2Days;
      case LanguageConceptSwitch.Return3Days:
        return myConceptReturn3Days;
      case LanguageConceptSwitch.Return5Days:
        return myConceptReturn5Days;
      case LanguageConceptSwitch.ReturnExpression:
        return myConceptReturnExpression;
      case LanguageConceptSwitch.ReturnMultiple:
        return myConceptReturnMultiple;
      case LanguageConceptSwitch.Rule:
        return myConceptRule;
      case LanguageConceptSwitch.Test:
        return myConceptTest;
      case LanguageConceptSwitch.TestParameterValue:
        return myConceptTestParameterValue;
      case LanguageConceptSwitch.Type:
        return myConceptType;
      case LanguageConceptSwitch.TypeBoolean:
        return myConceptTypeBoolean;
      case LanguageConceptSwitch.TypeDate:
        return myConceptTypeDate;
      case LanguageConceptSwitch.Value:
        return myConceptValue;
      case LanguageConceptSwitch.ValueBoolean:
        return myConceptValueBoolean;
      case LanguageConceptSwitch.ValueInteger:
        return myConceptValueInteger;
      case LanguageConceptSwitch.ValueMultiple:
        return myConceptValueMultiple;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAll() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "All", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f18730146ecL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Boolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028772460268");
    b.version(2);
    b.aggregate("ifConditions", 0x546a2f1873014757L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L).optional(false).ordered(true).multiple(true).origin("6082726028772460375").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAny() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Any", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73aa5L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Boolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934181");
    b.version(2);
    b.aggregate("ifConditions", 0xa41bf13b3c73abfL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L).optional(false).ordered(true).multiple(true).origin("739081905206934207").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBefore() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Before", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73acbL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Boolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934219");
    b.version(2);
    b.aggregate("date1", 0xa41bf13b3c73accL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1fL).optional(false).ordered(true).multiple(false).origin("739081905206934220").done();
    b.aggregate("date2", 0xa41bf13b3c73aceL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1fL).optional(false).ordered(true).multiple(false).origin("739081905206934222").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Boolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L);
    b.class_(false, true, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934023");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForComment() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Comment", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1cL);
    b.class_(false, false, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934044");
    b.version(2);
    b.property("commentText", 0xa41bf13b3c73a1dL).type(PrimitiveTypeId.STRING).origin("739081905206934045").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Date", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1fL);
    b.class_(false, true, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934047");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDatePicker() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "DatePicker", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a2aL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Date", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1fL);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934058");
    b.version(2);
    b.property("date", 0xa41bf13b3c73a35L).type(PrimitiveTypeId.STRING).origin("739081905206934069").done();
    b.alias("<date>");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForElseStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ElseStatement", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b71L);
    b.class_(false, false, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934385");
    b.version(2);
    b.aggregate("ifStatement", 0xa41bf13b3c73b72L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b44L).optional(false).ordered(true).multiple(false).origin("739081905206934386").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForIfStatement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "IfStatement", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b44L);
    b.class_(false, false, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934340");
    b.version(2);
    b.aggregate("comments", 0xa41bf13b3c73b54L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1cL).optional(false).ordered(true).multiple(true).origin("739081905206934356").done();
    b.aggregate("ifCondition", 0xa41bf13b3c73b5bL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L).optional(false).ordered(true).multiple(false).origin("739081905206934363").done();
    b.aggregate("returnExpression", 0xa41bf13b3c73b63L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L).optional(false).ordered(true).multiple(false).origin("739081905206934371").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Integer", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f18730469b1L);
    b.class_(false, false, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028772665777");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLessThan() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "LessThan", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ff68a3L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Boolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028772337827");
    b.version(2);
    b.aggregate("left", 0x546a2f1872ff68e9L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L).optional(false).ordered(true).multiple(false).origin("6082726028772337897").done();
    b.aggregate("right", 0x546a2f1872ff693cL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L).optional(false).ordered(true).multiple(false).origin("6082726028772337980").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMinus() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Minus", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x42575fae37fe2434L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ValueInteger", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/4780394731345421364");
    b.version(2);
    b.aggregate("left", 0x42575fae37fe243aL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L).optional(false).ordered(true).multiple(false).origin("4780394731345421370").done();
    b.aggregate("right", 0x42575fae37fe243cL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L).optional(false).ordered(true).multiple(false).origin("4780394731345421372").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForNotLessThan() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "NotLessThan", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1873015beeL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Boolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028772465646");
    b.version(2);
    b.aggregate("left", 0x546a2f1873015c45L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L).optional(false).ordered(true).multiple(false).origin("6082726028772465733").done();
    b.aggregate("right", 0x546a2f1873015c7dL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L).optional(false).ordered(true).multiple(false).origin("6082726028772465789").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameter() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Parameter", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73ad1L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934225");
    b.version(2);
    b.aggregate("type", 0xa41bf13b3c73ae3L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a59L).optional(false).ordered(true).multiple(false).origin("739081905206934243").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameterReferenceBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ParameterReferenceBoolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73aeaL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Boolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a07L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934250");
    b.version(2);
    b.associate("parameter", 0xa41bf13b3c73affL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73ad1L).optional(false).origin("739081905206934271").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameterReferenceDate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ParameterReferenceDate", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b01L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Date", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1fL);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934273");
    b.version(2);
    b.associate("parameter", 0xa41bf13b3c73b07L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73ad1L).optional(false).origin("739081905206934279").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForParameterReferenceInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ParameterReferenceInteger", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1873003de2L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ValueInteger", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028772392418");
    b.version(2);
    b.associate("parameter", 0x546a2f1873003e43L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73ad1L).optional(false).origin("6082726028772392515").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturn0Days() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Return0Days", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b23L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ReturnExpression", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934307");
    b.version(2);
    b.alias("0 days");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturn1Day() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Return1Day", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b2eL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ReturnExpression", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934318");
    b.version(2);
    b.alias("1 day");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturn2Days() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Return2Days", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b2fL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ReturnExpression", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934319");
    b.version(2);
    b.alias("2 days");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturn3Days() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Return3Days", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b30L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ReturnExpression", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934320");
    b.version(2);
    b.alias("3 days");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturn5Days() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Return5Days", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b31L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ReturnExpression", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934321");
    b.version(2);
    b.alias("5 days");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturnExpression() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ReturnExpression", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L);
    b.class_(false, true, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934071");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForReturnMultiple() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ReturnMultiple", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f187303504bL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.ReturnExpression", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028772593739");
    b.version(2);
    b.aggregate("values", 0x42575fae380a5555L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x42575fae380a4e1dL).optional(false).ordered(true).multiple(false).origin("4780394731346220373").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForRule() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Rule", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b74L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934388");
    b.version(2);
    b.aggregate("returnType", 0x546a2f1872f06c87L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73ad1L).optional(false).ordered(true).multiple(true).origin("6082726028771355783").done();
    b.aggregate("parameters", 0xa41bf13b3c73bb0L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73ad1L).optional(false).ordered(true).multiple(true).origin("739081905206934448").done();
    b.aggregate("comments", 0xa41bf13b3c73bb2L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1cL).optional(false).ordered(true).multiple(true).origin("739081905206934450").done();
    b.aggregate("ifStatement", 0xa41bf13b3c73bbfL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b44L).optional(false).ordered(true).multiple(false).origin("739081905206934463").done();
    b.aggregate("elseStatements", 0xa41bf13b3c73bc8L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b71L).optional(true).ordered(true).multiple(true).origin("739081905206934472").done();
    b.aggregate("defaultComments", 0xa41bf13b3c73bd7L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1cL).optional(false).ordered(true).multiple(true).origin("739081905206934487").done();
    b.aggregate("defaultReturn", 0xa41bf13b3c73be2L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a37L).optional(false).ordered(true).multiple(false).origin("739081905206934498").done();
    b.aggregate("unitTests", 0xa41bf13b3c73beeL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73c00L).optional(false).ordered(true).multiple(true).origin("739081905206934510").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Test", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73c00L);
    b.class_(false, false, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934528");
    b.version(2);
    b.aggregate("parameterComments", 0xa41bf13b3c73c06L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1cL).optional(false).ordered(true).multiple(true).origin("739081905206934534").done();
    b.aggregate("parameterValues", 0xa41bf13b3c73c08L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b09L).optional(false).ordered(true).multiple(true).origin("739081905206934536").done();
    b.aggregate("returnComments", 0xa41bf13b3c73c1aL).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a1cL).optional(false).ordered(true).multiple(true).origin("739081905206934554").done();
    b.aggregate("returnExpected", 0xa41bf13b3c73c23L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x42575fae380a4e1dL).optional(false).ordered(true).multiple(false).origin("739081905206934563").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestParameterValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "TestParameterValue", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73b09L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934281");
    b.version(2);
    b.aggregate("value", 0x546a2f1872ea8ec2L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872e9b1b8L).optional(false).ordered(true).multiple(false).origin("6082726028770971330").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForType() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Type", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a59L);
    b.class_(false, true, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934105");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTypeBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "TypeBoolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a64L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Type", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a59L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934116");
    b.version(2);
    b.alias("boolean");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTypeDate() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "TypeDate", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a7eL);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Type", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0xa41bf13b3c73a59L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/739081905206934142");
    b.version(2);
    b.alias("int");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValue() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "Value", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872e9b1b8L);
    b.class_(false, true, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028770914744");
    b.version(2);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValueBoolean() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ValueBoolean", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8ea8L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Value", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872e9b1b8L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028770971304");
    b.version(2);
    b.property("value", 0x546a2f1872ea8eaeL).type(PrimitiveTypeId.BOOLEAN).origin("6082726028770971310").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValueInteger() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ValueInteger", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872ea8eb5L);
    b.class_(false, false, false);
    b.super_("BusinessRules.structure.Value", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872e9b1b8L);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/6082726028770971317");
    b.version(2);
    b.property("value", 0x546a2f1872ea8ebbL).type(PrimitiveTypeId.INTEGER).origin("6082726028770971323").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValueMultiple() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("BusinessRules", "ValueMultiple", 0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x42575fae380a4e1dL);
    b.class_(false, false, false);
    b.origin("r:c8a36848-88f9-4c4d-b069-35490b489078(BusinessRules.structure)/4780394731346218525");
    b.version(2);
    b.aggregate("values", 0x42575fae380a4e23L).target(0xb885910aced43e1L, 0x8b6d9840b91c1156L, 0x546a2f1872e9b1b8L).optional(false).ordered(true).multiple(true).origin("4780394731346218531").done();
    return b.create();
  }
}
